// This code is part of the Fungus library (https://github.com/snozbot/fungus)
// It is released for free under the MIT open source license (https://github.com/snozbot/fungus/blob/master/LICENSE)

/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using Scaffold.Tutorial.Controllers;
using UnityEngine;

namespace Fungus
{
    /// <summary>
    /// TutorialController variable type.
    /// </summary>
    [VariableInfo("Tutorial", "TutorialProgressController")]
    [AddComponentMenu("")]
    [System.Serializable]
    public class TutorialProgressControllerVariable : VariableBase<TutorialProgressController>
    { }

    /// <summary>
    /// Container for a TutorialController variable reference or constant value.
    /// </summary>
    [System.Serializable]
    public struct TutorialProgressControllerData
    {
        [SerializeField]
        [VariableProperty("<Value>", typeof(TutorialProgressControllerVariable))]
        public TutorialProgressControllerVariable tutorialControllerRef;

        [SerializeField]
        public TutorialProgressController tutorialControllerVal;

        public static implicit operator TutorialProgressController(TutorialProgressControllerData tutorialProgressControllerData)
        {
            return tutorialProgressControllerData.Value;
        }

        public TutorialProgressControllerData(TutorialProgressController v)
        {
            tutorialControllerVal = v;
            tutorialControllerRef = null;
        }

        public TutorialProgressController Value
        {
            get { return (tutorialControllerRef == null) ? tutorialControllerVal : tutorialControllerRef.Value; }
            set { if (tutorialControllerRef == null) { tutorialControllerVal = value; } else { tutorialControllerRef.Value = value; } }
        }

        public string GetDescription()
        {
            if (tutorialControllerRef == null)
            {
                return tutorialControllerVal != null ? tutorialControllerVal.ToString() : "Null";
            }
            else
            {
                return tutorialControllerRef.Key;
            }
        }
    }
}
