<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>LiveOps.Modules.DTO</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <CopyDtoToUnityPlugins>true</CopyDtoToUnityPlugins>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    <PackageId>Game.LiveOps.Perks.DTO</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Deploy\Core\LiveOps.DTO\LiveOps.DTO.csproj" />
  </ItemGroup>
</Project>
