
/*This script has been, partially or completely, generated by the Scaffold.GenerateVariableWindow*/
using Scaffold.Tutorial.Controllers;
using UnityEngine;

namespace Scaffold
{
    /// <summary>
    /// TutorialController variable type.
    /// </summary>
    [VariableInfo("Tutorial", "TutorialProgressController")]
    [AddComponentMenu("")]
    [System.Serializable]
    public class TutorialProgressControllerVariable : VariableBase<TutorialProgressController>
    { }


}
