using System;
using GearEngine.Core.Actions;
/*This script has been, partially or completely, generated by the Scaffold.GenerateVariableWindow*/
using UnityEngine;


namespace Scaffold
{
    // <summary>
    /// Get or Set a property of a ControllerColliderHit component
    /// </summary>
    [CommandInfo("Property",
                 "ControllerColliderHit",
                 "Get or Set a property of a ControllerColliderHit component")]
    [Serializable]
    public class ControllerColliderHitProperty : BaseVariableProperty
    {
        //generated property
        public enum Property
        {
            Collider,
            Rigidbody,
            GameObject,
            Transform,
            Point,
            Normal,
            MoveDirection,
            MoveLength,
        }


        [SerializeField]
        protected Property property;

        [SerializeField]
        [VariableProperty(typeof(ControllerColliderHitVariable))]
        [Tooltip("The Controller collider hit var")]
        protected ControllerColliderHitVariable controllerColliderHitVar;

        [SerializeField]
        [VariableProperty(typeof(ColliderVariable),
                          typeof(RigidbodyVariable),
                          typeof(GameObjectVariable),
                          typeof(TransformVariable),
                          typeof(Vector3Variable),
                          typeof(FloatVariable))]
        [Tooltip("The In out var")]
        protected Variable inOutVar;

        public override void OnEnter()
        {
            ColliderVariable ioc = inOutVar as ColliderVariable;
            RigidbodyVariable iorb = inOutVar as RigidbodyVariable;
            GameObjectVariable iogo = inOutVar as GameObjectVariable;
            TransformVariable iot = inOutVar as TransformVariable;
            Vector3Variable iov = inOutVar as Vector3Variable;
            FloatVariable iof = inOutVar as FloatVariable;


            ControllerColliderHit target = controllerColliderHitVar.Value;

            switch (getOrSet)
            {
                case GetSet.Get:
                    switch (property)
                    {
                        case Property.Collider:
                            ioc.Value = target.collider;
                            break;
                        case Property.Rigidbody:
                            iorb.Value = target.rigidbody;
                            break;
                        case Property.GameObject:
                            iogo.Value = target.gameObject.gameObject;
                            break;
                        case Property.Transform:
                            iot.Value = target.gameObject.transform;
                            break;
                        case Property.Point:
                            iov.Value = target.point;
                            break;
                        case Property.Normal:
                            iov.Value = target.normal;
                            break;
                        case Property.MoveDirection:
                            iov.Value = target.moveDirection;
                            break;
                        case Property.MoveLength:
                            iof.Value = target.moveLength;
                            break;
                        default:
                            Debug.Log("Unsupported get or set attempted");
                            break;
                    }

                    break;
                case GetSet.Set:
                    switch (property)
                    {
                        default:
                            Debug.Log("Unsupported get or set attempted");
                            break;
                    }

                    break;
                default:
                    break;
            }

            Continue();
        }

        public override string GetSummary()
        {
            if (controllerColliderHitVar == null)
            {
                return "Error: no controllerColliderHitVar set";
            }
            if (inOutVar == null)
            {
                return "Error: no variable set to push or pull data to or from";
            }

            return getOrSet.ToString() + " " + property.ToString();
        }

        public override Color GetButtonColor()
        {
            return new Color32(235, 191, 217, 255);
        }

        public override bool HasReference(Variable variable)
        {
            if (controllerColliderHitVar == variable || inOutVar == variable)
            {
                return true;
            }

            return false;
        }

    }
}