using GearEngine.GearEngine.Presentation.UI.Tags;
using UnityEngine;

namespace GearEngine.GearEngine.Config
{
    public enum TrashZoneAlignment
    {
        Left,
        Center,
        Right
    }

    /// <summary>
    /// Design-time feature toggle for GearEngine optional mechanics.
    /// Assigned in the DI scope; read by views and view models to gate features.
    /// </summary>
    [CreateAssetMenu(menuName = "GearEngine/Feature Toggle", fileName = "GearEngineFeatureToggle")]
    public sealed class GearEngineFeatureToggleSO : ScriptableObject
    {
        [Header("Trash / Scrap Feature")]
        [Tooltip("Enables the drag-to-trash gear deletion mechanic.")]
        public bool EnableTrashDeletion = true;

        [Tooltip("Tag assigned to the trash drop zone for discovery by the drag handler.")]
        public TagSO TrashZoneTag;

        [Tooltip("Tag assigned to the inventory drop zone for discovery by the drag handler.")]
        public TagSO InventoryZoneTag;

        [Tooltip("Horizontal alignment of the trash zone relative to the grid.")]
        public TrashZoneAlignment TrashAlignment = TrashZoneAlignment.Right;

        [Tooltip("Icon sprite for the trash zone. Generated by Step 1 setup tool.")]
        public Sprite TrashIcon;
    }
}
